# Trafic Light Classificator

In [1]:
import cv2
import glob
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import tensorflow as tf
from keras.backend.tensorflow_backend import set_session
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.3
set_session(tf.Session(config=config))

/Users/azheng/anaconda3/envs/carnd-term1/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/azheng/anaconda3/envs/carnd-term1/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using TensorFlow backend.
/Users/azheng/anaconda3/envs/carnd-term1/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/azheng/anaconda3/envs/carnd-term1/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [3]:
%matplotlib inline

In [4]:
fig = plt.figure()


## 1. Data Import

In [5]:
X_train = []
x_label = []
for img_class, directory in enumerate(['red_Crop', 'yellow_Crop', 'green_Crop', 'none']):
    for i, file_name in enumerate(glob.glob("{}/*.jpg".format(directory))):
        file = cv2.imread(file_name)
        file = cv2.cvtColor(file, cv2.COLOR_BGR2RGB);
        resized = cv2.resize(file, (32,32))


        X_train.append(resized/255.-0.5)
        x_label.append(img_class)
        
        #if (i < 3):
        #    plt.imshow(rgb)
        #    plt.show()
        
X_train = np.array(X_train)
x_label = np.array(x_label)

In [116]:
x_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

## 2. CNN

In [6]:
from keras.models import Sequential
from keras.layers import Conv2D, Flatten, Dense, MaxPooling2D, Dropout, Activation
from keras.layers.convolutional import Convolution2D
from keras.utils.np_utils import to_categorical
from keras import losses, optimizers, regularizers


In [7]:
categorical_labels = to_categorical(x_label)

In [10]:
# num_classes = 4
# model = Sequential()
# model.add(Conv2D(32, (3, 3), input_shape=(64, 32, 3), padding='same', activation='relu', kernel_initializer='random_uniform', kernel_regularizer=regularizers.l2(0.01)))
# model.add(MaxPooling2D(2,2))
# Dropout(0.2)
# model.add(Flatten())

# #model.add(Dense(128, activation='relu', kernel_initializer='random_uniform', kernel_regularizer=regularizers.l2(0.01)))
# model.add(Dense(8, activation='relu', kernel_initializer='random_uniform', kernel_regularizer=regularizers.l2(0.01)))
# model.add(Dense(num_classes, activation='softmax'))

In [8]:
model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=(32, 32, 3), padding='same', activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Activation('relu'))
model.add(Flatten())
model.add(Dense(4))
model.add(Activation('softmax'))

In [77]:
# model = Sequential() # build sequential model of Nvidia NN
# model.add(Lambda(lambda x: x/255-0.5,input_shape=(160,320,3)))
# model.add(Cropping2D(cropping=((70,25),(0,0)))) # crop out the top 75 pixels, bottom 25 pixels, none n the outside
# model.add(Convolution2D(24,5,5,subsample=(2,2),activation="relu")) # 1st conv layer of 24 filters, 5x5 stride, relu activation
# model.add(Convolution2D(36,5,5,subsample=(2,2),activation="relu")) # 2nd conv layer of 36 filters, 5x5 stride, relu activation
# model.add(Convolution2D(48,5,5,subsample=(2,2),activation="relu")) # 3rd conv layer of 48 filters, 5x5 stride, relu activation
# model.add(Convolution2D(64,3,3,activation="relu")) # 4th conv layer of 64 filters, 3x3 stride, relu activation
# model.add(Convolution2D(64,3,3,activation="relu")) # 5th conv layer of 64 filters, 3x3 stride, relu activation
# model.add(Flatten()) # flatten input into single array
# model.add(Dense(100)) # fully connected layer with output of 100
# model.add(Dense(50))  # fully connected layer with output of 50
# model.add(Dense(10))  # fully connected layer with output of 10
# model.add(Dense(1))	 # fully connected layer with output of 1

In [9]:
loss = losses.categorical_crossentropy
optimizer = optimizers.Adam()

In [10]:
model.compile(loss=loss, optimizer=optimizer, metrics=['accuracy'])

In [11]:
model.fit(X_train, categorical_labels, batch_size=64, epochs=30, verbose=True, validation_split=0.1, shuffle=True)

Train on 718 samples, validate on 80 samples
Epoch 1/30
718/718 [==============================] - 0s - loss: 0.9935 - acc: 0.6045 - val_loss: 8.2953 - val_acc: 0.0625
Epoch 2/30
718/718 [==============================] - 0s - loss: 0.6357 - acc: 0.7827 - val_loss: 12.4242 - val_acc: 0.0625
Epoch 3/30
718/718 [==============================] - 0s - loss: 0.4303 - acc: 0.8691 - val_loss: 14.7704 - val_acc: 0.0625
Epoch 4/30
718/718 [==============================] - 0s - loss: 0.2922 - acc: 0.9192 - val_loss: 14.9979 - val_acc: 0.0625
Epoch 5/30
718/718 [==============================] - 0s - loss: 0.1878 - acc: 0.9680 - val_loss: 15.0865 - val_acc: 0.0625
Epoch 6/30
718/718 [==============================] - 0s - loss: 0.1272 - acc: 0.9805 - val_loss: 15.1122 - val_acc: 0.0625
Epoch 7/30
718/718 [==============================] - 0s - loss: 0.0977 - acc: 0.9847 - val_loss: 15.1122 - val_acc: 0.0625
Epoch 8/30
718/718 [==============================] - 0s - loss: 0.0824 - acc: 0.9861 - 

In [12]:
score = model.evaluate(X_train, categorical_labels, verbose=0)

In [13]:
print(score)

[1.518769020093885, 0.9060150375939849]


In [14]:
prediction = model.predict(X_train, verbose=1)
for i in range(len(prediction)):
    print (i, prediction[i], categorical_labels[i])

768/798 [===========================>..] - ETA: 0s0 [9.8000622e-01 1.6706379e-02 3.2875265e-03 5.5291449e-13] [1. 0. 0. 0.]
1 [9.9214047e-01 5.5480669e-03 2.3115368e-03 7.8374529e-12] [1. 0. 0. 0.]
2 [9.7873574e-01 1.8742019e-02 2.5222998e-03 1.8742572e-11] [1. 0. 0. 0.]
3 [9.6808463e-01 2.9504331e-02 2.4110598e-03 5.4636084e-11] [1. 0. 0. 0.]
4 [9.9567199e-01 3.6769628e-03 6.5105339e-04 2.2443767e-11] [1. 0. 0. 0.]
5 [9.9927360e-01 6.7318033e-04 5.3191103e-05 2.9959832e-12] [1. 0. 0. 0.]
6 [9.9941206e-01 5.5568496e-04 3.2302432e-05 1.8870745e-12] [1. 0. 0. 0.]
7 [9.992281e-01 6.764827e-04 9.546965e-05 4.089288e-12] [1. 0. 0. 0.]
8 [9.9844474e-01 1.2326012e-03 3.2262047e-04 1.3081150e-11] [1. 0. 0. 0.]
9 [9.99212742e-01 6.72219729e-04 1.15052986e-04 7.22284515e-12] [1. 0. 0. 0.]
10 [9.9856806e-01 1.1911537e-03 2.4085061e-04 1.3106918e-11] [1. 0. 0. 0.]
11 [9.9922347e-01 6.5399345e-04 1.2253615e-04 7.6578804e-12] [1. 0. 0. 0.]
12 [9.9920964e-01 7.0735440e-04 8.3068851e-05 6.1117409e-12]

370 [1.3628171e-04 9.9952614e-01 3.3764806e-04 9.5190088e-12] [0. 1. 0. 0.]
371 [4.8242300e-03 9.9441755e-01 7.5823377e-04 6.8226640e-11] [0. 1. 0. 0.]
372 [1.7967631e-04 9.9912566e-01 6.9469365e-04 7.9989010e-12] [0. 1. 0. 0.]
373 [1.0986411e-04 9.9884182e-01 1.0483061e-03 1.2046357e-11] [0. 1. 0. 0.]
374 [9.7186996e-05 9.9494582e-01 4.9569816e-03 1.6315735e-11] [0. 1. 0. 0.]
375 [9.1419934e-05 9.9607855e-01 3.8300056e-03 1.1696806e-11] [0. 1. 0. 0.]
376 [7.3463505e-04 9.8758531e-01 1.1680009e-02 1.6335204e-10] [0. 1. 0. 0.]
377 [1.7435990e-03 9.9571937e-01 2.5370193e-03 1.6914264e-10] [0. 1. 0. 0.]
378 [7.0779002e-05 9.9561995e-01 4.3092603e-03 1.5078170e-11] [0. 1. 0. 0.]
379 [9.8547542e-05 9.9956459e-01 3.3689488e-04 8.7585763e-12] [0. 1. 0. 0.]
380 [1.9081209e-04 9.9835432e-01 1.4548587e-03 9.9067777e-12] [0. 1. 0. 0.]
381 [6.6913868e-05 9.9904126e-01 8.9181797e-04 6.3222552e-12] [0. 1. 0. 0.]
382 [1.3395974e-04 9.9919480e-01 6.7123777e-04 1.6388725e-11] [0. 1. 0. 0.]
383 [1.38450

536 [5.6916665e-06 2.7733229e-06 9.9999154e-01 2.8869861e-17] [0. 0. 1. 0.]
537 [8.2691076e-06 2.3698124e-06 9.9998939e-01 3.0320458e-17] [0. 0. 1. 0.]
538 [4.6373493e-06 7.4803276e-05 9.9992049e-01 1.2322473e-16] [0. 0. 1. 0.]
539 [2.6095954e-06 6.4074603e-04 9.9935669e-01 1.0187247e-16] [0. 0. 1. 0.]
540 [4.2945508e-06 2.9214445e-07 9.9999547e-01 7.4562272e-19] [0. 0. 1. 0.]
541 [2.12667674e-05 1.14931415e-08 9.99978781e-01 1.35793485e-19] [0. 0. 1. 0.]
542 [1.4684533e-13 1.5732465e-13 1.0000000e+00 1.2740716e-23] [0. 0. 1. 0.]
543 [1.8172200e-10 2.2588015e-08 1.0000000e+00 7.7643163e-21] [0. 0. 1. 0.]
544 [9.9312876e-12 6.8025696e-09 1.0000000e+00 6.9186166e-22] [0. 0. 1. 0.]
545 [7.3648416e-06 4.8443284e-03 9.9514836e-01 4.0703729e-11] [0. 0. 1. 0.]
546 [2.7412707e-05 1.7109089e-02 9.8286349e-01 1.1337538e-10] [0. 0. 1. 0.]
547 [1.1925032e-05 1.9632464e-02 9.8035562e-01 1.1971800e-10] [0. 0. 1. 0.]
548 [5.2911105e-07 1.1500359e-04 9.9988449e-01 2.3773769e-12] [0. 0. 1. 0.]
549 [3.5

In [60]:
#plt.imshow(X_train[0])
#out = np.array(X_train[0]*255, dtype=np.uint8)
#out = cv2.cvtColor(out, cv2.COLOR_RGB2BGR)


In [62]:
#cv2.imwrite('Train_test.jpg',out)
#X_train[0]

array([[[0.2745098 , 0.29411765, 0.31764706],
        [0.2627451 , 0.29019608, 0.31372549],
        [0.2627451 , 0.29019608, 0.31372549],
        ...,
        [0.25098039, 0.27058824, 0.31372549],
        [0.25098039, 0.27058824, 0.29411765],
        [0.25490196, 0.2745098 , 0.29803922]],

       [[0.25882353, 0.27843137, 0.30196078],
        [0.26666667, 0.28627451, 0.30980392],
        [0.27058824, 0.29019608, 0.30980392],
        ...,
        [0.24313725, 0.25882353, 0.30196078],
        [0.24705882, 0.27058824, 0.30196078],
        [0.2627451 , 0.27843137, 0.31372549]],

       [[0.26666667, 0.29019608, 0.30588235],
        [0.25882353, 0.27843137, 0.30588235],
        [0.25882353, 0.27843137, 0.30196078],
        ...,
        [0.24313725, 0.25882353, 0.29803922],
        [0.23921569, 0.26666667, 0.30588235],
        [0.25490196, 0.28235294, 0.32156863]],

       ...,

       [[0.39607843, 0.39215686, 0.37647059],
        [0.37647059, 0.36862745, 0.36862745],
        [0.36470588, 0

In [124]:
import h5py
model.save('classifier_carla.h5')

In [15]:
file = cv2.imread('Green_test.jpg')
file = cv2.cvtColor(file, cv2.COLOR_BGR2RGB);
file.shape
resized = cv2.resize(file, (32,32))
resized = resized/255.0-0.5
prediction = model.predict(resized.reshape((1, 32, 32, 3)))
prediction

array([[1.3635009e-04, 4.9739196e-05, 9.9981397e-01, 1.7403500e-14]],
      dtype=float32)

(32, 32, 3)