# Trafic Light Classificator

In [52]:
import cv2
import glob
import matplotlib.pyplot as plt
import numpy as np

In [53]:
import tensorflow as tf
from keras.backend.tensorflow_backend import set_session
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.3
set_session(tf.Session(config=config))

In [4]:
%matplotlib inline

In [5]:
fig = plt.figure()


## 1. Data Import

In [115]:
X_train = []
x_label = []
for img_class, directory in enumerate(['red_Crop', 'yellow_Crop', 'green_Crop', 'none']):
    for i, file_name in enumerate(glob.glob("{}/*.jpg".format(directory))):
        file = cv2.imread(file_name)
        file = cv2.cvtColor(file, cv2.COLOR_BGR2RGB);
        resized = cv2.resize(file, (32,32))


        X_train.append(resized/255.-0.5)
        x_label.append(img_class)
        
        #if (i < 3):
        #    plt.imshow(rgb)
        #    plt.show()
        
X_train = np.array(X_train)
x_label = np.array(x_label)

In [116]:
x_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

## 2. CNN

In [56]:
from keras.models import Sequential
from keras.layers import Conv2D, Flatten, Dense, MaxPooling2D, Dropout, Activation
from keras.layers.convolutional import Convolution2D
from keras.utils.np_utils import to_categorical
from keras import losses, optimizers, regularizers


In [117]:
categorical_labels = to_categorical(x_label)

In [10]:
# num_classes = 4
# model = Sequential()
# model.add(Conv2D(32, (3, 3), input_shape=(64, 32, 3), padding='same', activation='relu', kernel_initializer='random_uniform', kernel_regularizer=regularizers.l2(0.01)))
# model.add(MaxPooling2D(2,2))
# Dropout(0.2)
# model.add(Flatten())

# #model.add(Dense(128, activation='relu', kernel_initializer='random_uniform', kernel_regularizer=regularizers.l2(0.01)))
# model.add(Dense(8, activation='relu', kernel_initializer='random_uniform', kernel_regularizer=regularizers.l2(0.01)))
# model.add(Dense(num_classes, activation='softmax'))

In [113]:
model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=(32, 32, 3), padding='same', activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Activation('relu'))
model.add(Flatten())
model.add(Dense(4))
model.add(Activation('softmax'))

In [77]:
# model = Sequential() # build sequential model of Nvidia NN
# model.add(Lambda(lambda x: x/255-0.5,input_shape=(160,320,3)))
# model.add(Cropping2D(cropping=((70,25),(0,0)))) # crop out the top 75 pixels, bottom 25 pixels, none n the outside
# model.add(Convolution2D(24,5,5,subsample=(2,2),activation="relu")) # 1st conv layer of 24 filters, 5x5 stride, relu activation
# model.add(Convolution2D(36,5,5,subsample=(2,2),activation="relu")) # 2nd conv layer of 36 filters, 5x5 stride, relu activation
# model.add(Convolution2D(48,5,5,subsample=(2,2),activation="relu")) # 3rd conv layer of 48 filters, 5x5 stride, relu activation
# model.add(Convolution2D(64,3,3,activation="relu")) # 4th conv layer of 64 filters, 3x3 stride, relu activation
# model.add(Convolution2D(64,3,3,activation="relu")) # 5th conv layer of 64 filters, 3x3 stride, relu activation
# model.add(Flatten()) # flatten input into single array
# model.add(Dense(100)) # fully connected layer with output of 100
# model.add(Dense(50))  # fully connected layer with output of 50
# model.add(Dense(10))  # fully connected layer with output of 10
# model.add(Dense(1))	 # fully connected layer with output of 1

In [78]:
loss = losses.categorical_crossentropy
optimizer = optimizers.Adam()

In [119]:
model.compile(loss=loss, optimizer=optimizer, metrics=['accuracy'])

In [120]:
model.fit(X_train, categorical_labels, batch_size=64, epochs=30, verbose=True, validation_split=0.1, shuffle=True)

Train on 718 samples, validate on 80 samples
Epoch 1/30
718/718 [==============================] - 0s - loss: 0.7715 - acc: 0.7214 - val_loss: 14.4317 - val_acc: 0.0625
Epoch 2/30
718/718 [==============================] - 0s - loss: 0.2310 - acc: 0.9123 - val_loss: 15.0952 - val_acc: 0.0625
Epoch 3/30
718/718 [==============================] - 0s - loss: 0.0801 - acc: 0.9805 - val_loss: 15.1108 - val_acc: 0.0625
Epoch 4/30
718/718 [==============================] - 0s - loss: 0.0408 - acc: 0.9916 - val_loss: 15.1108 - val_acc: 0.0625
Epoch 5/30
718/718 [==============================] - 0s - loss: 0.0318 - acc: 0.9916 - val_loss: 15.1107 - val_acc: 0.0625
Epoch 6/30
718/718 [==============================] - 0s - loss: 0.0177 - acc: 0.9958 - val_loss: 15.1107 - val_acc: 0.0625
Epoch 7/30
718/718 [==============================] - 0s - loss: 0.0133 - acc: 1.0000 - val_loss: 15.1107 - val_acc: 0.0625
Epoch 8/30
718/718 [==============================] - 0s - loss: 0.0073 - acc: 1.0000 -

In [121]:
score = model.evaluate(X_train, categorical_labels, verbose=0)

In [122]:
print(score)

[1.5159364472767225, 0.9060150375939849]


In [123]:
prediction = model.predict(X_train, verbose=1)
for i in range(len(prediction)):
    print (i, prediction[i], categorical_labels[i])

768/798 [===========================>..] - ETA: 0s0 [9.9760771e-01 2.3490668e-03 4.3148339e-05 5.9956862e-20] [1. 0. 0. 0.]
1 [9.9756253e-01 2.3817951e-03 5.5701385e-05 6.4569560e-17] [1. 0. 0. 0.]
2 [9.92347717e-01 7.54112937e-03 1.11175395e-04 9.11943067e-17] [1. 0. 0. 0.]
3 [9.8999935e-01 9.9091176e-03 9.1591668e-05 1.7403222e-15] [1. 0. 0. 0.]
4 [9.9895048e-01 1.0035074e-03 4.6025943e-05 1.0999025e-15] [1. 0. 0. 0.]
5 [9.9981564e-01 1.8154131e-04 2.8329821e-06 4.1010579e-17] [1. 0. 0. 0.]
6 [9.9979597e-01 2.0227098e-04 1.7314721e-06 2.7232351e-17] [1. 0. 0. 0.]
7 [9.9972779e-01 2.6805024e-04 4.2033184e-06 1.4996525e-16] [1. 0. 0. 0.]
8 [9.9955589e-01 4.2461374e-04 1.9378806e-05 5.5519812e-16] [1. 0. 0. 0.]
9 [9.9977523e-01 2.1889618e-04 5.8265082e-06 3.3824522e-16] [1. 0. 0. 0.]
10 [9.9962783e-01 3.5946519e-04 1.2622693e-05 6.4306614e-16] [1. 0. 0. 0.]
11 [9.9978799e-01 2.0490773e-04 7.1232430e-06 3.6854721e-16] [1. 0. 0. 0.]
12 [9.9982762e-01 1.6788171e-04 4.4183971e-06 1.5909803e

348 [1.10775385e-04 9.99268353e-01 6.20822597e-04 1.58964240e-15] [0. 1. 0. 0.]
349 [9.6926458e-05 9.9684554e-01 3.0574461e-03 1.0577862e-15] [0. 1. 0. 0.]
350 [2.477583e-04 9.992028e-01 5.495170e-04 3.627402e-15] [0. 1. 0. 0.]
351 [4.7240712e-05 9.9848396e-01 1.4688020e-03 1.4935196e-15] [0. 1. 0. 0.]
352 [3.4393772e-05 9.9906451e-01 9.0111606e-04 3.0519201e-15] [0. 1. 0. 0.]
353 [4.3594373e-05 9.9888784e-01 1.0686176e-03 2.4795437e-15] [0. 1. 0. 0.]
354 [4.4428813e-05 9.9887091e-01 1.0846627e-03 1.6601752e-15] [0. 1. 0. 0.]
355 [7.28227460e-05 9.99819577e-01 1.07633256e-04 7.94066058e-17] [0. 1. 0. 0.]
356 [5.6342291e-05 9.9943572e-01 5.0791650e-04 1.6331654e-16] [0. 1. 0. 0.]
357 [1.0867497e-04 9.9941707e-01 4.7433338e-04 2.4710145e-16] [0. 1. 0. 0.]
358 [5.5157285e-05 9.9984932e-01 9.5455238e-05 2.5910373e-16] [0. 1. 0. 0.]
359 [5.7288249e-05 9.9968159e-01 2.6108822e-04 1.4998292e-16] [0. 1. 0. 0.]
360 [6.4809421e-05 9.9983370e-01 1.0145806e-04 2.4653018e-16] [0. 1. 0. 0.]
361 [1.7

518 [6.4694525e-08 3.5534816e-07 9.9999952e-01 8.9749576e-23] [0. 0. 1. 0.]
519 [7.7581745e-09 2.7262911e-07 9.9999976e-01 2.9674054e-23] [0. 0. 1. 0.]
520 [4.7203770e-09 3.0518009e-08 1.0000000e+00 5.6039693e-25] [0. 0. 1. 0.]
521 [1.6272534e-07 3.0933827e-06 9.9999678e-01 3.7568421e-22] [0. 0. 1. 0.]
522 [1.9356338e-07 2.7072188e-06 9.9999702e-01 4.2066941e-22] [0. 0. 1. 0.]
523 [5.5178194e-08 3.7082266e-09 1.0000000e+00 3.0758347e-24] [0. 0. 1. 0.]
524 [2.0528100e-07 7.7508851e-08 9.9999964e-01 3.4610243e-24] [0. 0. 1. 0.]
525 [3.2007012e-08 1.2550106e-08 1.0000000e+00 6.4521717e-25] [0. 0. 1. 0.]
526 [4.2141146e-06 1.7917699e-07 9.9999559e-01 7.7776738e-23] [0. 0. 1. 0.]
527 [3.1438628e-08 5.3620548e-09 1.0000000e+00 6.2278054e-25] [0. 0. 1. 0.]
528 [8.4607547e-07 3.0159736e-08 9.9999917e-01 2.5551847e-23] [0. 0. 1. 0.]
529 [3.1549201e-09 1.9560520e-09 1.0000000e+00 1.6296353e-25] [0. 0. 1. 0.]
530 [1.3716482e-08 5.8412047e-10 1.0000000e+00 2.4902099e-26] [0. 0. 1. 0.]
531 [4.89271

In [60]:
#plt.imshow(X_train[0])
#out = np.array(X_train[0]*255, dtype=np.uint8)
#out = cv2.cvtColor(out, cv2.COLOR_RGB2BGR)


In [62]:
#cv2.imwrite('Train_test.jpg',out)
#X_train[0]

array([[[0.2745098 , 0.29411765, 0.31764706],
        [0.2627451 , 0.29019608, 0.31372549],
        [0.2627451 , 0.29019608, 0.31372549],
        ...,
        [0.25098039, 0.27058824, 0.31372549],
        [0.25098039, 0.27058824, 0.29411765],
        [0.25490196, 0.2745098 , 0.29803922]],

       [[0.25882353, 0.27843137, 0.30196078],
        [0.26666667, 0.28627451, 0.30980392],
        [0.27058824, 0.29019608, 0.30980392],
        ...,
        [0.24313725, 0.25882353, 0.30196078],
        [0.24705882, 0.27058824, 0.30196078],
        [0.2627451 , 0.27843137, 0.31372549]],

       [[0.26666667, 0.29019608, 0.30588235],
        [0.25882353, 0.27843137, 0.30588235],
        [0.25882353, 0.27843137, 0.30196078],
        ...,
        [0.24313725, 0.25882353, 0.29803922],
        [0.23921569, 0.26666667, 0.30588235],
        [0.25490196, 0.28235294, 0.32156863]],

       ...,

       [[0.39607843, 0.39215686, 0.37647059],
        [0.37647059, 0.36862745, 0.36862745],
        [0.36470588, 0

In [124]:
import h5py
model.save('classifier_carla.h5')

In [69]:
file = cv2.imread('Green_test.jpg')
file = cv2.cvtColor(file, cv2.COLOR_BGR2RGB);
file.shape
resized = cv2.resize(file, (32,32))
resized = resized/255.0-0.5
prediction = model.predict(resized.reshape((1, 32, 32, 3)))
prediction

array([[2.0118935e-03, 9.1601530e-04, 9.9707198e-01, 7.8336504e-12]],
      dtype=float32)

(32, 32, 3)